### ISSUE TITLE
Bad issue title

### ISSUE THREAD

**Issue by SirMathhman** [magfmur/Website#1]
Hi.
Why did you make this repo public?

**Comment by magfmur** [comment]
> Hi.
> Why did you make this repo public?

Hi!

Repo is public in order to share with people who may review and find issues with my beginner HTML/CSS/JavaScript.

As it's something I'm relatively new at, it helps to have others who are more experienced take a look and share their advice on what I can do to make improvements.

Building a portfolio is important for me, no matter how "bad" the content may be at the moment. For those reasons listed, I chose to and will continue to make this repo public.

- Nate Stutte
